services:
  wordpress:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    depends_on:
      - db
    env_file: // <.>
      - ../.env
    ports:
      - "${WORDPRESS_PORT}:80"
    extra_hosts: // <.>
      - localhost:host-gateway
    volumes:
      - ..:/app

  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: ${WORDPRESS_DB_NAME}
      MYSQL_ROOT_PASSWORD: ${WORDPRESS_DB_ROOT_PASSWORD}
    volumes:
      - mysql-data:/var/lib/mysql

  pma:
    image: phpmyadmin
    depends_on:
      - db
    ports:
      - "${PMA_PORT}:80"
    environment:
      PMA_USER: ${WORDPRESS_DB_USER}
      PMA_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      UPLOAD_LIMIT: 100M
      MYSQL_ROOT_PASSWORD: ${WORDPRESS_DB_ROOT_PASSWORD}

volumes:
  mysql-data:
