version: "3.1"
services:
  site:
    image: wordpress:php8.1-apache
    depends_on:
      - db
    ports:
      - "${WORDPRESS_PORT}:80"
    extra_hosts:
      - localhost:host-gateway
    environment:
      WORDPRESS_HOME: ${WORDPRESS_HOME}
      WORDPRESS_SITEURL: ${WORDPRESS_SITEURL}
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
      WORDPRESS_CONFIG_EXTRA_FILE: ${WORDPRESS_CONFIG_EXTRA_FILE}
      WORDPRESS_CONFIG_EXTRA: ${WORDPRESS_CONFIG_EXTRA}
      APACHE_RUN_USER: "#${UID}"
      APACHE_RUN_GROUP: "#${GID}"
    volumes:
      - ${WORDPRESS_SOURCES}:/var/www/html

  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: ${WORDPRESS_DB_NAME}
      MYSQL_ROOT_PASSWORD: ${WORDPRESS_DB_ROOT_PASSWORD}
    volumes:
      - wpdb:/var/lib/mysql

  pma:
    image: phpmyadmin
    depends_on:
      - db
    ports:
      - "${PMA_PORT}:80"
    environment:
      PMA_USER: ${WORDPRESS_DB_USER}
      PMA_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      UPLOAD_LIMIT: 100M
      MYSQL_ROOT_PASSWORD: ${WORDPRESS_DB_ROOT_PASSWORD}

volumes:
  wpdb:
