# Antora playbook for local development
# In this version, source urls point to local copies of the content repositories

site:
  title: My documentation
  url: https://rolfkleef.github.io
  start_page: overview::index.adoc

# Run `git worktree add build/site site` to check out the Github Pages branch here:
output:
  dir: ./build/site

content:
  sources:
  - url: .
    branches: main
    start_paths:
    - docs/overview
    - docs/documentation_system
    - docs/styleguide

  - url: /home/rolf/dev/tools/antora/antora-ui
    branches: drostan
    start_path: docs_drostan
    
  - url: /home/rolf/dev/desktop
    branches: main
    start_paths: 
    - docs/public

ui:
  bundle:
    url: /home/rolf/dev/tools/antora/antora-ui/build/ui-bundle.zip
    snapshot: true
  supplemental_files:
  - path: ui.yml
    contents: |
      static_files: [ .nojekyll ]
  - path: .nojekyll
  
# tag::asciidoc[]
asciidoc:
  extensions:
  - asciidoctor-kroki # <1>
  attributes:
    page-pagination: true
    hide-uri-scheme: true # <2>
    kroki-fetch-diagram: true # <3>
    allow-uri-read: true
    experimental: true
    kroki-default-format@: svg
    kroki-server-url: http://localhost:18181 # <4>
# end::asciidoc[]
    _yamldoc: >
      tag::asciidoc-notes[]
      <1> Use kroki to generate diagram images
      <2> Don't show https:// etc on bare links
      <3> For kroki: store the image. This requires `allow-uri-read`, as well as `experimental` (to override kroki security)
      <4> To run  a local kroki server: `docker run -p18181:8000 -d --name asciidoctor-kroki yuzutech/kroki`
      end::asciidoc-notes[]


    # to be copied to each localhost playbook...
    # tag::header[]
    page-brand: rolf@drostan.org # <1>
    page-sections: # <2>
    - title: My documentation
      url: /index.html
    # end::header[]
    _yamldoc1: >
      tag::header-notes[]
      <1> Name to put in the brand section of the header
      <2> Each main section to include, with absolute URL
      end::header-notes[]
