= Ruby and Rails

== Setup

My current Ruby setup runs these services:

app:: A Ruby development server,
with a local source directory added as _bind mount_.
It runs a Puma web server,
and a Sidekiq server for background jobs,
such as sending emails.

db:: A Postgres server,
with its database stored on a Docker volume.

redis:: A Redis server.

pgadmin:: A PgAdmin server,
to manage the Postgres database(s).
* A Chrome server to run headless Selenium tests.

chrome:: A Chrome server to run headless Selenium tests.

[plantuml]
----
frame docker-compose {
  frame app {
    control puma
    control sidekiq
    puma .. sidekiq
  }
  component mailcatcher
  component pgadmin
  component chrome
  database redis
  database db
  storage pgdata as "docker\nvolume"

  puma --> db
  app -- redis
  puma --> redis
  redis <- sidekiq
  puma <--- chrome
  pgadmin --> db
  db --> pgdata
}

folder local as "local directory"
puma <- local: bind mount
----

Configuration remarks:

[CAUTION]
====
The local directory is added via a bind mount,
but nothing has been done yet to test
how files uploaded to the server are handled.
====

* The app server will be built within the container.
My local machine has no Ruby or Yarn installed.
* This creates a problem with providing an updated
`Gemfile.lock` or `yarn.lock`,
or having up to date `node_modules`.
My workaround is to run a bash shell in the container,
with a bind of my local directory,
to install new a Gem or NPM package.
* Some of the Gems come from private GitHub repositories.
It is therefore necessary to pass an access token,
using Docker secrets,
and to supply them to `bundle` as environment variable.
+
[source,dockerfile]
----
RUN --mount=type=secret,id=github_user \
  --mount=type=secret,id=github_token \
  BUNDLE_GITHUB__COM=$(cat /run/secrets/github_user):$(cat /run/secrets/github_token) bundle install
----

== Example files

..env
[source,bash]
----
include::example$ruby/env[]
----

.docker-compose.yml
[source,yaml]
----
include::example$ruby/docker-compose.yml[]
----

.Dockerfile
[source,dockerfile]
----
include::example$ruby/Dockerfile[]
----
