<style>
mindmapDiagram {
  node {
    BackgroundColor #1168bd
    LineColor #1168bd
    FontColor #fff
    MaximumWidth 150
  }
  boxless {
    FontColor #1168bd
  }
  arrow {
    LineColor #e91e63
  }
}
wbsDiagram {
  node {
    BackgroundColor #1168bd
    LineColor #1168bd
    FontColor #fff
    MaximumWidth 100
  }
  boxless {
    FontColor #1168bd
  }
  arrow {
    LineColor #e91e63
  }
}
</style>
