version: "3"

services:
  antora:
    image: node:16-buster
    command: sleep infinity
    volumes:
      - ..:/drostan/notes

  kroki:
    image: yuzutech/kroki
    depends_on:
      - mermaid
    environment:
      - KROKI_MERMAID_HOST=mermaid

  mermaid:
    image: yuzutech/kroki-mermaid
