= Documentation tools

There are several choices for (technical) documentation tools.

Key is how to combine a suitable source syntax standard with a way to generate documentation as websites or documents.

== Source syntax options

* On my laptop, I use https://zim-wiki.org/[Zim] as a wiki for notes.
+
It has several useful features to function as a general notebook:

** Intuitive WYSIWYG interface with automatic save, tags, links.
** Journal feature to keep weekly notes.
** Task list feature to track tasks and todo's.
** Ability to overlay it on top of existing files and folders, to keep notes and see "attachments" per folder.
** With a keyboard shortcut available _at hand_ to quickly take notes.

+
It also has some drawbacks:

** It has its own text-based syntax.
** It has decent options to export notes to a site, but it still is quite some work.

* Most current projects use some version of _markdown_. I use it as well.
+
** It's a simple format suitable for common needs.
** Anything beyond relatively simple requirements requires platform-specific versions and plugins.
** There is no standardised way to extend markdown.

* More thorough standards like _DITA_ and _DocBook_ provide better semantic markup.
+
** But... there are few reasonable options to edit those XML-based formats.
** The toolchain to produce reasonable documentation is hard to use.

* Text-based alternatives that offer better technical documentation support:

** ReStructuredText is popular in the Python world, and offers better semantic markup support.
** AsciiDoc is another option, closely aligned to _DITA_ in terms of semantics.
It seems to have more standardised ways to extend its syntax.

== Source repository options

All text-based syntax formats make it easy to use common version control tools to keep track of documentation.

However, almost all tools to generate a static site rely on the documentation sources to be present in a single repository.

* For _markdown_ there are several options:

** Github Pages works with Jekyll, a popular tool to transform _markdown_ sources into a website.

** Hugo is another popular option, again transforming _markdown_ into a website.

* In a broader sense, there are new options:

** Gatsby and Next.JS can generate static sites based on a variety of sources, but require considerable more effort to get started.

** Antora is an opiniated option to combine Asciidoc sources from multiple repositories.
 
=== Github Pages

* With a bit of planning, it is possible to combine multiple repositories into a single documentation site.

** It is still possible to _Jekyll_ or another tool to transform a source syntax into HTML pages.

** _Jekyll_ comes out of the box, but Hugo and other options can now be used through Github Actions.

A coherent site mostly depends on a suitable theme for the sites generated.

Standard Github Pages makes it easy to publish a _general_ website for a set of repositories in a single organisation.

=== Antora

Antora addresses the situation where you deal not only with multiple repositories,
but likely also with repositories spread across organisations,
as well as with documentation for different versions.

* _Antora_ can be used to create multiple sites and layouts from the same content sources.

** This is mostly similar to the Github Pages approach: create an interface repository that is used across sub-sites. 

* _Antora_ creates some additional logic to regular AsciiDoc, and sometimes changes default behaviour. 

== Decision

_Jekyll_, _markdown_, and _Github Pages_ provide a reasonably simple workflow to create a website based on multiple repositories and an interface.

_Antora_ and _Asciidoc_ provide a similar workflow, with a separate interface, and with more deployment options.

