= Zotero

https://www.zotero.org[Zotero^] is a reference manager to keep track of the work of others.
We use Zotero as a *content helper* to generate lists of background reading or additional information on documentation pages.

== System overview

[CAUTION]
====
This is a _works-for-me solution_ that could eventually be replaced by an Asciidoc macro, an Antora pipeline component,
and/or a bibtex-based approach, to be more in line with common practice.

This version does not build a bibliography based on in-text references, it just creates a list as HTML file to be included.
There is no way to cross reference or link between the text and a specific reference.
====

.Zotero subsystem overview
[plantuml]
....
@startuml
!include <C4/C4_Container>

Person(editor, "Editor", "Writes and reviews documentation content.")

System_Boundary(doc_sys, "Documentation system") {
  System_Boundary(sources, "Content sources") {
    Container(source_repo, "Source repository", "git, asciidoc", "Manages documentation content files.")
    Container(content_helper, "Zotero content helper", "get-zoteros", "Generates reference lists for specified Zotero references.")
    Rel_R(content_helper, source_repo, "gets Zotero lookup details and stores partials in Antora modules")
  }
  
  System_Boundary(sitegen, "Website generator") {
    Container(antora, "Site generator", "antora, asciidoctor", "Gathers sources, produces a static website, and deploys it.")
  }
  Rel_D(source_repo, antora, "provides content for")
}

System_Ext(zotero, "Zotero", "Manages references and bibliographic information.")

Rel(editor, source_repo, "2) adds Zotero lookup details to")
Rel(editor, source_repo, "4) includes partials in pages in")
Rel(editor, zotero, "1) organises references in")
Rel_L(content_helper, zotero, "retrieves HTML-formatted references from")

Rel(editor, content_helper, "3) runs")

@enduml
....

== Activities

The *editor* performs a few tasks.

. <<step1>>
. <<step2>>
. <<step3>>
. <<step4>>

[#step1]
=== Organise references in Zotero

Zotero lets you organise references in _collections_ and label them with _tags_.
Both can be used to later retrieve a set of references from Zotero.
We use a _collection_ for each page.
footnote:[Zotero references can be part of multiple collections.]

It is possible to move collections around in Zotero without changing their identifier.
This decouples the exact hierarchy and organisation of collections in Zotero from the documentation pages.

.Current organisation of collections in Zotero
[plantuml]
....
@startmindmap
include::styleguide:visual_style:partial$plantuml-wbsmm-style.iuml[]
* Library
 * (other collections)
  *_ ...
 * References used
  * Documentation site
   * Page 1
    *_ Reference 1
    *_ Reference 2
    *_ ...
   * Page 2
    *_ ...
  * (other publications)
   *_ ...
@endmindmap
....

[#step2]
=== Add Zotero lookup details to the content

Each content component can have a file called `zotero` in the same folder as the `antora.yml` file.
This file contains a list of reference lists to generate.

.A `zotero` file with two lists
[source, text]
....
collections/NAN7TETL/ ROOT background-refs # <1>
collections/JBHC442F/ module1 further-reading mytag # <2>
....
<1> Get all references in the collection, and add them as `background-refs.html` to the `partials` folder of the `ROOT` module.
<2> Get references in the collection with tag `mytag`, and add them as `further-reading.html` to the `partials` folder of the `module1` module.

TIP: The collection id can be found in the web address https://www.zotero.org/rolfkleef/collections/NAN7TETL[when visiting the collection online^]. 

[#step3]
=== Run the content helper

The content helper `get-zoteros` is a script that can be run in a component folder.
See below for the script itself.
It will process the `zoteros` file and use the Zotero API to do two retrievals:

. Get an HTML-formatted list of references using a specified CSL file.
footnote:[https://citationstyles.org/[See the Citation Style Language website for available styles^]]
. Add the same list formatted as COinS, to let readers quickly add the references to their own reference manager.
footnote:[https://en.wikipedia.org/wiki/COinS[ContextObjects in Spans (COinS) embeds bibliographic metadata as HTML code.^]]

The resulting HTML file is stored in the `partials` folder of a module.
This partial file is also included in version control, so the helper only needs to be run when references have changed.

[#step4]
=== Include the reference list in a page

The reference list can be added to a page with a simple Asciidoc `include` statement in a pass-through block.

.Add the references to an Asciidoc page
[source, asciidoc]
....
++++
\include::partials$background-refs.html[]
++++
....

== Content helper script

.The `get-zoteros` script
[source, bash]
....
include::../examples/get-zoteros.sh[]
....
<1> Replace `12345` with the appropriate user id. The user id can be found https://www.zotero.org/settings/keys[on Zotero's Feeds/API settings page^].
<2> Replace the URL of the CSL file with the desired style definition.

The https://www.zotero.org/support/dev/web_api/v3/basics[Zotero API documentation^] can help to change the API call to your liking.


