= Git
:suborder: 2

Offical documentation: http://git-scm.com/documentation

Cheat sheet: http://help.github.com/git-cheat-sheets/

=== Configuration

User configuration is typically in `~/.gitconfig`

==== Aliases

Useful abbrevaviations for common commands

[source,ini]
----
[alias]
  st = status
  di = diff
  co = checkout
  ci = commit
----

==== Push tags

Automatically push tags: when pushing commits, tags associated with those commits will be pushed as well.

[source,ini]
----
[push]
  followTags = true
----

To push all tags manually

[source,bash]
----
git push --tags
----

=== Helpers

Use http://paulfitz.github.io/daff/[daff] as "data diff" to compare CSV files.
Add the `--www` switch to the config to open a CSV diff in a web page.

Use https://www.npmjs.com/package/npm-merge-driver[npm-merge-driver] to merge package-lock.json files when merging a branch into another (for instance when finishing a feature branch).

In `~/.gitconfig`

[source,ini]
----
[diff "daff-csv"]
  command = daff diff --www --git
[merge "daff-csv"]
  name = daff tabular csv merge
  driver = daff merge --output %A %O %A %B
	
[merge "npm-merge-driver"]
  name = automatically merge npm lockfiles
  driver = npx npm-merge-driver merge %A %O %B %P
----

And in `~/.config/git/attributes`

[source,ini]
----
*.csv diff=daff-csv
*.csv merge=daff-csv

npm-shrinkwrap.json merge=npm-merge-driver
package-lock.json merge=npm-merge-driver
----

== Typical tasks

=== Remove the last commit

If you have committed junk but not pushed,

[source,bash]
----
git reset --hard HEAD~1
----

`HEAD~1` is a shorthand for the commit before head.
Alternatively you can refer to the SHA-1 of the hash you want to reset to.
Note that when using `--hard` any changes to tracked files in the working tree since the commit before head are lost.

If you don't want to wipe out the work you have done, you can use `--soft` option that will delete the commit but it will leave all your changed files "Changes to be committed", as git status would put it.

Now if you already pushed and someone pulled which is usually my case, you can't use git reset.
You can however do a git revert,

[source,sh]
----
git revert HEAD
----

This will create a new commit that reverses everything introduced by the accidental commit.

== Change a commit

You can use git rebase, for example, if you want to modify commit bbc643cd, run

[source,bash]
----
git rebase bbc643cd^ --interactive
----

In the default editor, modify 'pick' to 'edit' in the line whose commit you want to modify.

Make any changes and stage them with git add, git rm etc.

Now you can use

[source,bash]
----
git commit --amend
----

to modify the commit, and after that

[source,bash]
----
git rebase --continue
----

to return back to the previous head commit.

== Other tips and tricks

=== Configuration

==== insteadOf

Use alternative names for base URLs

[source,ini]
----
[url "loginname@example.com:/path/to/repos"]
  insteadOf = "myExamples:"
----

You can then clone a repository with

[source,bash]
----
git clone myExamples:mywork.git
----

If the repositories move to another location, you only need to update your config file.

=== Shell enhancement

==== Git in the shell prompt

To get an indicator of `git status` in the command line prompt:

Add this to (for instance) .bashrc:

[source,bash]
----
GIT_PS1_SHOWDIRTYSTATE=true
GIT_PS1_SHOWUNTRACKEDFILES=true
GIT_PS1_SHOWSTASHSTATE=true
----

And add something like this to your prompt:

[source,bash]
----
$(__git_ps1 "[\[\e[0;32m\]%s\[\e[0m\]]")
----

The git status will be presented in the command line prompt in green in a format like this:

----
... [master *$%>] ...
----

This contains a number of indicators:

* the branch you are on: master
* local files have changed: *
* there is stuff in the stash: $
* there are local 'untracked' files: %
* your local copy is ahead of the remote: >

=== Partially clone repository

Clone only a single branch from the remote (default: origin/master)

[source,bash]
----
git clone <url> --branch <branch> --single-branch [<folder>]
----

=== Shared (bare) repositories

To share with a unix group:

[source,bash]
----
git repo-config core.sharedRepository group
----

To share with both group and world:

[source,bash]
----
git repo-config core.sharedRepository all
----

In `.git/config`:

[source,ini]
----
core.sharedRepository: true
----

* When `group` (or `true`), the repository is made shareable between several users in a group (making sure all the files and objects are group-writable).
* When `all` (or `world` or `everybody`), the repository will be readable by all users, additionally to being group-shareable.
* When `umask` (or `false`), git will use permissions reported by umask(2).
When `0xxx`, where 0xxx is an octal number, files in the repository will have this mode value.
0xxx will override user's umask value (whereas the other options will only override requested parts of the user's umask value).
Examples:
 ** `0660` will make the repo read/write-able for the owner and group, but inaccessible to others (equivalent to group unless umask is e.g.
0022).
 ** `0640` is a repository that is group-readable but not group-writable.

See git-init(1).
`false` by default.

== Submodules

A submodule has a few parts:

* the module is registered in .gitmodules
* it refers to another repository
* the submodule looks like a single file to the host repository (containing the commit-id of the repository in the submodule)

=== Setup after cloning

if you clone a repository with submodules, you first need to initialise those:

[source,bash]
----
git submodule init
----

after that, you can update submodules to their current versions using

[source,bash]
----
git submodule update
----

=== Update git submodules in other submodules

[source,bash]
----
git submodule update --init --recursive
----

=== Changes in a submodule

If you change something in a submodule, `git status` will report it as a file change.

For a local change, you will:

* restore the submodule in its original change
* or commit and push the change, and then add and commit the "pseudo file change" in the main project

For a remote change, you will:

* use `git submodule update` to import remote changes
