name: Generate notes website
on:
  push:
    branches:
      - main
  workflow_dispatch:
    
jobs:
  antora:
    runs-on: ubuntu-latest
    container: node:22-bookworm
    
    services:
      kroki:
        image: yuzutech/kroki
        env:
          KROKI_MERMAID_HOST: mermaid
      mermaid:
        image: yuzutech/kroki-mermaid

    steps:
      - name: Get the sources
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: Setup Antora
        run: npm ci --production

      - name: Generate main notes site
        run: npm run notes

      - name: Deploy site
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/site
          publish_branch: site
